weblingtools/weblingtools_app/views.py
# encoding: utf-8
'''
Created on 12 apr. 2017

@author: brandaoc

Defines the methods/endpoints (the views) of the userprofile service.
This defines the interaction points, but the actual logic is treated
by the :mod:`controller`.
'''
from __future__ import unicode_literals
from __future__ import absolute_import

import os

import warnings

#Flask and modules
from flask import Blueprint
from flask import render_template
from flask import request
from flask import send_file
from werkzeug.utils import secure_filename

from lingtools.util import get_vectorspaces


import errno

import config 

#Exceptions and errors
#from flask.ext.api.exceptions import AuthenticationFailed, ParseError
#from sqlalchemy.orm.exc import NoResultFound
#from .errors import *

#Python modules
#import datetime
#import json
#import time
#import simplejson

#Import controller
from weblingtools_app import controller

#Extensions
#from .extensions import LOG

#Logging
import logging
LOG = logging.getLogger(__name__)

# blueprint
weblingtools_blueprint = Blueprint('weblingtools_blueprint', __name__, url_prefix='')
#error_pages = Blueprint('error_pages', __name__)

# Filename treatment
def allowed_file(fileobj):
    filename = fileobj.filename
    mimetype = fileobj.mimetype
    if ('.' in filename) and (filename.rsplit('.', 1)[1].lower() in config.ALLOWED_EXTENSIONS) and (mimetype in config.ALLOWED_MIMETYPES):
        return True
    else:
        return False  


################################

@weblingtools_blueprint.route('/')
def index(name=None):
    '''
    Says hello.
    '''
    #return 'Hello world!'
    return render_template('index.html', name=name)

@weblingtools_blueprint.route('/help')
def helppage(name=None):
    '''
    Help page.
    '''
    #return 'Hello world!'
    return render_template('help.html', name=name)



@weblingtools_blueprint.route('/simple', methods=['POST', 'GET'])
def process_simple(name=None):
    '''
    Processes the text and shows results.
    '''
    errormsg = None
    warningmsg = None
    
    # Get available vector spaces
    vec_spaces = get_vectorspaces()

    if request.method == 'POST':
        input_text = request.form['text']
        vectorspace_name = request.form['vectorspace_name']

        # Clean up new lines in incoming string
        input_text = "\n".join(input_text.splitlines())
         
        
        # Process text
        result = controller.process_text(input_text, vectorspace_name=vectorspace_name)
        #LOG.debug("The result that will be sent to the view: %r", result) 
        
        # generate file for download
        #file_for_download = 'helloworld.txt'
        
        # Return result
        #return render_template('results.html', errormsg=errormsg, result = result, text = input_text, file_for_download=file_for_download)
        return render_template('results.html', errormsg=errormsg, result = result, text = input_text)
    
    else:
        return render_template('simple.html', 
                               name=name, 
                               errormsg=errormsg, 
                               warningmsg=warningmsg, 
                               max_text_size=config.MAX_TEXT_SIZE,
                               vectorspaces=vec_spaces)
    


@weblingtools_blueprint.route('/file', methods=['GET', 'POST'])
def process_file(name=None):
    '''  
    Page that receives a text file for analysis of several texts at once.
    '''
    errormsg = None
    warningmsg = None
    
    # Get available vector spaces
    vec_spaces = get_vectorspaces()
    
    if request.method == 'POST':
        # check if the post request has the file part
        if 'file' not in request.files:
            errormsg = 'Bad request: no file'
            return render_template('error.html', errormsg=errormsg), 400
        myfile = request.files['file']
        vectorspace_name = request.form['vectorspace_name']
        
        # if user does not select file, browser also
        # submit a empty part without filename
        if myfile.filename == '':
            errormsg = 'Bad request: no selected file'
            return render_template('error.html', errormsg=errormsg), 400
        if myfile and allowed_file(myfile): 

            
            # Save file locally
            uploaded_filename = os.path.join(config.UPLOAD_FOLDER, secure_filename(myfile.filename))
            myfile.save(uploaded_filename)
            LOG.info('File uploaded: %s', uploaded_filename)
            
            # Get file type
            filetype = request.form['fileformat']
            LOG.info("Filetype: {}".format(filetype))
            if int(filetype) in [1,2,3,4]:
                filetype = int(filetype)
            else:
                filetype = 1 # Default is one document per line
            
            # Process file and get filename of processed csv
            resulting_file = controller.process_file(uploaded_filename, filetype, vectorspace_name=vectorspace_name)
            
            # Return the results
            return render_template('results_file.html', name=name, file_for_download=resulting_file)

                
        else:
            fileextension = myfile.filename.split('.')[-1]
            errormsg = 'File type not allowed'
            LOG.warning( 'User tried to send file not allowed: %s', fileextension)
            return render_template('error.html', errormsg=errormsg), 400
            
    else:
        max_file_size = config.MAX_CONTENT_LENGTH
        return render_template('file.html', 
                               name=name, 
                               max_file_size=max_file_size, 
                               errormsg=errormsg, 
                               warningmsg=warningmsg,
                               vectorspaces=vec_spaces)

@weblingtools_blueprint.route('/download/<filename>')
def download_file(filename=None):
    if filename:
        LOG.info( "Serving file: %s", filename)
        try:
            return send_file(os.path.join(config.RESULTS_FOLDER, filename), as_attachment=True, mimetype="text/csv", attachment_filename="results.csv")
        except EnvironmentError as e:
            LOG.error(e)
            if e.errno == errno.ENOENT:
                errormsg = "File does not exist or expired"
                return render_template('error.html', errormsg=errormsg), 404
            else:
                raise e
    else:
        errormsg = 'Invalid request'
        return render_template('file.html', errormsg=errormsg), 400

 
@weblingtools_blueprint.route('/dynamicthemes', methods=['GET', 'POST'])
def dynamic_themes(name=None):
    errormsg = None
    warningmsg = None
    
    # Get available vector spaces
    vec_spaces = get_vectorspaces()
    
    if request.method == 'POST':
        
        theme_name = request.form['theme_name']
        theme_words = request.form['theme_words']
        vectorspace_name = request.form['vectorspace_name']
        #input_text = request.form['text']
        
        # Split theme words
        theme_words = theme_words.replace(',', "\n")
        theme_words = theme_words.splitlines()
        
        # check if the post request has the file part
        if 'file' not in request.files:
            errormsg = 'Bad request: no file'
            return render_template('error.html', errormsg=errormsg), 400
        myfile = request.files['file']
        
        # if user does not select file, browser also
        # submit a empty part without filename
        if myfile.filename == '':
            errormsg = 'Bad request: no selected file'
            return render_template('error.html', errormsg=errormsg), 400
        if myfile and allowed_file(myfile):
            
            # Save file locally
            uploaded_filename = os.path.join(config.UPLOAD_FOLDER, secure_filename(myfile.filename))
            myfile.save(uploaded_filename)
            LOG.info('File uploaded: %s', uploaded_filename)
            
            # Get file type
            filetype = request.form['fileformat']
            LOG.info("Filetype: {}".format(filetype))
            if int(filetype) in [1,2,3,4]:
                filetype = int(filetype)
            else:
                filetype = 1 # Default is one document per line
                
            # Get encoding
            encoding = request.form['encoding']
            
            warningmsgs = []
            
            with warnings.catch_warnings(record=True) as all_warnings:
                # Cause all warnings to always be triggered
                warnings.simplefilter("always")
                
                
                # Process file and get filename of processed csv
                resulting_file = controller.process_dynamic_themes(theme_name, 
                                                                   theme_words, 
                                                                   uploaded_filename, 
                                                                   filetype, 
                                                                   encoding=encoding,
                                                                   vectorspace_name=vectorspace_name)
                
                # ignore any non-custom warnings that may be in the list
                #w = filter(lambda i: issubclass(i.category, UserWarning), w)
    
    
                if len(all_warnings):
                    for w in all_warnings:
                        warningmsgs.append(str(w.message))
                    
                if len(warningmsgs)>0:
                    LOG.warning(warningmsgs)
            
            if len(warningmsgs)>0:
                warningmsg = '. '.join(warningmsgs)
            
            # Return the results
            return render_template('results_file.html', name=name, file_for_download=resulting_file, errormsg=errormsg, warningmsg=warningmsg)
        else:
            fileextension = myfile.filename.split('.')[-1]

weblingtools/weblingtools_app/templates/base.html
{% block doc -%}
<!DOCTYPE html>
<html{% block html_attribs %}{% endblock html_attribs %}>
{%- block html %}
  <head>
    {%- block head %}
    <title>Linguistic tools for Cognitive Science - {% block title %}{% endblock title %}</title>

    {%- block metas %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {%- endblock metas %}

    {%- block styles %}
    <!-- Bootstrap -->
    <link href="{{bootstrap_find_resource('css/bootstrap.css', cdn='bootstrap')}}" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='lingtools.css')}}">
    {%- endblock styles %}
    
    {% import "bootstrap/fixes.html" as fixes %}
    
    {{fixes.ie8()}}
    
    <script type=text/javascript>
        $SCRIPT_ROOT = {{ request.script_root|tojson|safe }};
    </script>
    
    
    {%- endblock head %}
  </head>
  
  <body{% block body_attribs %}{% endblock body_attribs %}>
  
  
  
    {% block body -%}
    <!-- Wrap all page content here -->
    <div class="wrapper" id="wrap">
    
    {% block navbar %}
    
    {{nav.top.render()}}
    
    {%- endblock navbar %}
    
    <div class="row">
    <div class="col-xs-12 col-md-12 col-lg-12">
        <h1>Linguistic tools for Cognitive Science (alpha)</h1>
    </div> <!--/col-->
    </div> <!--/row-->
   
    
    {% block content -%}


    {%- endblock content %}

    {% block scripts %}
    <script src="{{bootstrap_find_resource('jquery.js', cdn='jquery')}}"></script>
    <script src="{{bootstrap_find_resource('js/bootstrap.js', cdn='bootstrap')}}"></script>
    {%- endblock scripts %}
    
    
    </div> <!--/wrapper-->
    {%- endblock body %}
    
  </body>
  
{%- endblock html %}
</html>
{% endblock doc -%}

weblingtools/weblingtools_app/templates/cosinedist.html
{% extends "base.html" %}
{% block content %}

<div class="row">
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

    <h2>Cosine distances matrix</h2>
    
    
    
    {% if errormsg %}
        <div class="alert alert-warning" role="alert">
            <strong>Error:</strong> {{ errormsg }}
        </div>  
    {% endif %} 
    
    {% if warningmsg %}
        <div class="alert alert-info" role="alert">
            <strong>Warning:</strong> {{ warningmsg }}
        </div>  
    {% endif %} 
    
    
    
    <p>This page calculates a matrix of cosine distances between the lines of a file. </p>
    
    
    <p>Each line is considered a document, and each document can contain one word or multiple words.</p>
    
    
    <form action="{{ url_for('weblingtools_blueprint.cosine_distances') }}" method="post" enctype="multipart/form-data">
    
    <p class="help-block">Select a file to analyze.</p>
    
    <div class="form-group col-sm-8 col-md-8 col-lg-8">     
        <label for="file">File (.txt only)</label>
        <input type="file" name="file" id="file"> 
        <p class="help-block">Maximum file size: {{max_file_size | filesizeformat}}</p>
    </div>
    
    <div class="form-group col-sm-12 col-md-12 col-lg-12">
        <label for="fileformat">File format</label>
        <div class="radio">
            <label>
            <input type="radio" name="fileformat" id="fileformat" value="1" checked />One document per line, no paragraphs
            </label>
        </div>
<!--        <div class="radio">
            <label>
            <input type="radio" name="fileformat" id="fileformat" value="2" />Single document, new line is a new paragraph
            </label>
        </div>
        <div class="radio">
            <label>
            <input type="radio" name="fileformat" id="fileformat" value="3" />Single document, empty line is a new paragraph
            </label>
        </div>

        <div class="radio">
            <label>
            <input type="radio" name="fileformat" id="fileformat" value="4" />Zipped file with multiple documents, one document per file, empty line is a new paragraph
            </label>
        </div>
-->
    </div>
    
    <div class="clearfix"></div>
        
        
    	
     <div class="clearfix"></div>
    
    <div class="form-group col-sm-4 col-md-4">
        <label for="encoding">File encoding</label>
        <select class="form-control" name="encoding" id="encoding">
            <option value="utf-8">UTF-8</option>
            <option value="iso8859-1">Latin 1 (ISO 8859-1)</option>
            <option value="cp1252">Windows (CP-1252)</option>
            <option value="auto">Other/autodetect</option>
        </select>
        <p class="help-block">Defaults to UTF-8. If you have issues, try "Other/autodetect". Be warned that it might give you unexpected results!</p>
    </div>
    
     <div class="clearfix"></div>
    
    <div class="form-group col-sm-4 col-md-4">
        <label for="language">Language</label>
        <select class="form-control" name="language" id="language">
            <option value="english">English</option>
            <!--<option value="dutch">Dutch</option>-->
        </select>
    </div>
    
     <div class="clearfix"></div>
    
	<div class="form-group col-sm-4 col-md-4">
	        <label for="vectorspace_name">Vector space</label>
	        <select class="form-control" name="vectorspace_name" id="vectorspace_name">
	        {% for vs in vectorspaces %}
	            <option value="{{vs.name}}">{{vs.name}}: {{vs.description}}</option>
	        {% endfor %}
	        </select>
	        <p class="help-block">Choose the desired vector space</p>
    	</div>
    	
     <div class="clearfix"></div>
     
    <div class="form-group col-sm-12 col-md-12 col-lg-12">
        <input type="submit" class="btn btn-default" value="Analyze" />
    </div>

    </div>
    </form>

</div> <!--/col-->    
</div><!--/row-->
    
{% endblock %}

weblingtools/weblingtools_app/templates/distinctivewords_results.html
{% extends "base.html" %}
{% block content %}


<div class="row">
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

<h2>Distinctive words extractor - Results</h2>

    {% if errormsg %}
        <div class="alert alert-warning" role="alert">
            <strong>Error:</strong> {{ errormsg }}
        </div>  
    {% endif %} 
    
    {% if warningmsg %}
        <div class="alert alert-info" role="alert">
            <strong>Warning:</strong> {{ warningmsg }}
        </div>  
    {% endif %} 
    
{% if file_for_download %}

<div class="panel panel-default col-xs-12 col-sm-8 col-md-4 col-lg-4">
  <div class="panel-heading">Download results </div>
    <div class="panel-body">
<p><a href="/download/{{ file_for_download }}">Download results</a> (link will expire after 15 minutes)</p>
  </div>
</div>
<div class="clearfix"></div>
{% endif %}

{% if result %}



    <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
    
    <table class="table table-condensed table-hover">
        <thead> 
            <tr> 
                <th>Word</th> 
                <th>Chi-square</th> 
                <th>P-Value</th>
                <th>Word rate (per 1000) in file 1</th>  
                <th>Word rate (per 1000) in file 2</th>                            
            </tr> 
        </thead> 
        <tbody>
        {% for item in result %}
            <tr style="background-color: {{item.color}}">
                <td>{{ item.word }}</td>
                <td>{{ '%0.3f'| format(item.chisq|float)  }}</td>
                <td>{{ '%0.3f'| format(item.pval|float)  }}</td>  
                <td>{{ '%0.3f'| format(item.rate1|float)  }}</td>
                <td>{{ '%0.3f'| format(item.rate2|float)  }}</td>                    
            </tr>
        {% endfor %}
        </tbody>
    </table>
    </div>

<div class="clearfix"></div>

<div class="panel panel-default col-xs-12 col-sm-8 col-md-4 col-lg-4">
  <div class="panel-heading">Color code</div>
  <div class="panel-body">
    <span style="background: {{color1}}">File 1 has higher rate</span>, <span style="background: {{color2}}">File 2 has higher rate</span><p>
  </div>
</div>
<div class="clearfix"></div>

{% endif %}
    
</div> <!--/col-->    
</div><!--/row-->

{% endblock %}

weblingtools/weblingtools_app/templates/dynamicthemes.html
{% extends "base.html" %}
{% block content %}

<div class="row">
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

    <h2>Dynamic themes analyzer</h2>
    
    {% if errormsg %}
        <div class="alert alert-warning" role="alert">
            <strong>Error:</strong> {{ errormsg }}
        </div>  
    {% endif %} 
    
    {% if warningmsg %}
        <div class="alert alert-info" role="alert">
            <strong>Warning:</strong> {{ warningmsg }}
        </div>  
    {% endif %} 
    
    <p>Calculates cosine distances between a theme and one or more documents.</p>
    
   
    <form action="{{ url_for('weblingtools_blueprint.dynamic_themes') }}" method="post"  enctype="multipart/form-data">
    
    	<div class="form-group col-sm-8 col-md-8 col-lg-8"> 
            <label for="theme_name">Theme name:</label>
            <input class="form-control"  id="theme_name" name="theme_name" placeholder="Theme name" />
        </div>
    
    	<div class="form-group col-sm-8 col-md-8 col-lg-8"> 
            <label for="theme_words">Theme words (separate with commas or one per line, max {{max_number_theme_words}} words):</label>
            <textarea  class="form-control" rows=5 id="theme_words" name="theme_words" placeholder="Theme words (separate with commas or one per line)"></textarea>
        </div>
           
    
    
    <div class="form-group col-sm-8 col-md-8 col-lg-8">     
        <label for="file">File (.txt only)</label>
        <input type="file" name="file" id="file"> 
        <p class="help-block">Maximum file size: {{max_file_size | filesizeformat}}</p>
    </div>
    
    <div class="form-group col-sm-12 col-md-12 col-lg-12">
        <label for="fileformat">File format</label>
        <div class="radio">
            <label>
            <input type="radio" name="fileformat" id="fileformat" value="1" checked />One document per line, no paragraphs
            </label>
        </div>
        
        <div class="radio">
            <label>
            <input type="radio" name="fileformat" id="fileformat" value="2" />Single document, new line is a new paragraph
            </label>
        </div>
        <div class="radio">
            <label>
            <input type="radio" name="fileformat" id="fileformat" value="3" />Single document, empty line is a new paragraph
            </label>
        </div>
<!--
        <div class="radio">
            <label>
            <input type="radio" name="fileformat" id="fileformat" value="4" />Zipped file with multiple documents, one document per file, empty line is a new paragraph
            </label>
        </div>
-->
    </div>
    
    <div class="form-group col-sm-4 col-md-4">
        <label for="encoding">File encoding</label>
        <select class="form-control" name="encoding" id="encoding">
            <option value="utf-8">UTF-8</option>
            <option value="iso8859-1">Latin 1 (ISO 8859-1)</option>
            <option value="cp1252">Windows (CP-1252)</option>
            <option value="auto">Other/autodetect</option>
        </select>
        <p class="help-block">Defaults to UTF-8. If you have issues, try "Other/autodetect". Be warned that it might give you unexpected results!</p>
    </div>
    
    <div class="clearfix"></div>
    
    <div class="form-group col-sm-4 col-md-4">
        <label for="language">Language</label>
        <select class="form-control" name="language" id="language">
            <option value="english">English</option>
            <!--<option value="dutch">Dutch</option>-->
        </select>
    </div>
    
	<div class="clearfix"></div>
        
        <div class="form-group col-sm-4 col-md-4">
	        <label for="vectorspace_name">Vector space</label>
	        <select class="form-control" name="vectorspace_name" id="vectorspace_name">
	        {% for vs in vectorspaces %}
	            <option value="{{vs.name}}">{{vs.name}}: {{vs.description}}</option>
	        {% endfor %}
	        </select>
	        <p class="help-block">Choose the desired vector space</p>
    	</div>
    
        <div class="form-group col-sm-12 col-md-12 col-lg-12">
            <input type="submit" class="btn btn-default" value="Analyze" />
        </div>

    
    </form>    
    
    
</div> <!--/col-->    
</div><!--/row-->
    
{% endblock %}

weblingtools/weblingtools_app/templates/error.html
{% extends "base.html" %}
{% block content %}

<div class="row">
<div class="col-xs-12 col-sm-12 col-md-8 col-lg-6">

    <h2>Error</h2>

    <div class="alert alert-danger" role="alert">
        <b>{{ errormsg }}.</b> Please <a href="javascript: window.history.go(-1);">go back</a> and try again.
    </div>  


</div> <!--/col-->    
</div><!--/row-->

{% endblock %}

weblingtools/weblingtools_app/templates/file.html
{% extends "base.html" %}
{% block content %}

<div class="row">
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

    <h2>Bulk text feature extraction</h2>
    
    {% if errormsg %}
        <div class="alert alert-warning" role="alert">
            <strong>Error:</strong> {{ errormsg }}
        </div>  
    {% endif %} 
    
    {% if warningmsg %}
        <div class="alert alert-info" role="alert">
            <strong>Warning:</strong> {{ warningmsg }}
        </div>  
    {% endif %} 
    

    <p>Here you can extract several linguistic features from an uploaded file (with one or more documents).</p>
    
    <p>The list of features extracted by the tool (and their ranges) can be found in the <a href="/help">Help</a> page.</p>
    

    
    <form action="{{ url_for('weblingtools_blueprint.process_file') }}" method="post" enctype="multipart/form-data">
    
    <p class="help-block">Select a file to analyze.</p>
    
    <div class="form-group col-sm-8 col-md-8 col-lg-8">     
        <label for="file">File (.txt only)</label>
        <input type="file" name="file" id="file"> 
        <p class="help-block">Maximum file size: {{max_file_size | filesizeformat}}</p>
    </div>
    
    <div class="form-group col-sm-12 col-md-12 col-lg-12">
        <label for="fileformat">File format</label>
        <div class="radio">
            <label>
            <input type="radio" name="fileformat" id="fileformat" value="1" checked />One document per line, no paragraphs
            </label>
        </div>
        <div class="radio">
            <label>
            <input type="radio" name="fileformat" id="fileformat" value="2" />Single document, new line is a new paragraph
            </label>
        </div>
        <div class="radio">
            <label>
            <input type="radio" name="fileformat" id="fileformat" value="3" />Single document, empty line is a new paragraph
            </label>
        </div>
<!--
        <div class="radio">
            <label>
            <input type="radio" name="fileformat" id="fileformat" value="4" />Zipped file with multiple documents, one document per file, empty line is a new paragraph
            </label>
        </div>
-->
    </div>
    
    <div class="form-group col-sm-4 col-md-4">
        <label for="encoding">File encoding</label>
        <select class="form-control" name="encoding" id="encoding">
            <option value="utf-8">UTF-8</option>
            <option value="iso8859-1">Latin 1 (ISO 8859-1)</option>
            <option value="cp1252">Windows (CP-1252)</option>
            <option value="auto">Other/autodetect</option>
        </select>
        <p class="help-block">Defaults to UTF-8. If you have issues, try "Other/autodetect". Be warned that it might give you unexpected results!</p>
    </div>
    
    <div class="clearfix"></div>
    
    <div class="form-group col-sm-4 col-md-4">
        <label for="language">Language</label>
        <select class="form-control" name="language" id="language">
            <option value="english">English</option>
            <!--<option value="dutch">Dutch</option>-->
        </select>
    </div>
    
    <div class="clearfix"></div>
        
        <div class="form-group col-sm-4 col-md-4">
	        <label for="vectorspace_name">Vector space</label>
	        <select class="form-control" name="vectorspace_name" id="vectorspace_name">
	        {% for vs in vectorspaces %}
	            <option value="{{vs.name}}">{{vs.name}}: {{vs.description}}</option>
	        {% endfor %}
	        </select>
	        <p class="help-block">Choose the desired vector space</p>
    </div>
    

    <div class="form-group col-sm-12 col-md-12 col-lg-12">
        <input type="submit" class="btn btn-default" value="Analyze" />
    </div>

    </div>
    </form>

</div> <!--/col-->    
</div><!--/row-->
    
{% endblock %}

weblingtools/weblingtools_app/templates/index.html
{% extends "base.html" %}
{% block content %}

<div class="row">
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

    {% if errormsg %}
        <div class="alert alert-warning" role="alert">
            <strong>Error:</strong> {{ errormsg }}
        </div>  
    {% endif %} 
    
    {% if warningmsg %}
        <div class="alert alert-info" role="alert">
            <strong>Warning:</strong> {{ warningmsg }}
        </div>  
    {% endif %} 

    <h2>Welcome to the Linguistic Tools for Cognitive Science web app.</h2>
    
    <p><b>This is an alpha release of the tool! If you run into problems, check the Help page.</b>
    
    <p>You have the following options:</p>
        
    <ul>
    
    <li><b><a href={{ url_for('weblingtools_blueprint.process_simple') }}>Simple text feature extraction</a>: </b>
    Extracts linguistic features from a text.</li>
    
    <li><b><a href={{ url_for('weblingtools_blueprint.process_file') }}>Bulk text feature extraction</a>: </b>
    Extracts linguistic features from an uploaded file (with one or more documents).</li>
    
    <li><b><a href={{ url_for('weblingtools_blueprint.dynamic_themes') }}>Dynamic themes analysis</a>: </b>
    Calculates cosine distances between a theme and one or more documents.</li>
    
    <li><b><a href={{ url_for('weblingtools_blueprint.distinctive_words') }}>Distinctive words extractor</a>: </b>
    Given two sets of texts, calculates the words that most distinguish the two.</li>
    
    <li><b><a href={{ url_for('weblingtools_blueprint.cosine_distances') }}>Cosine distances</a>: </b>
    Given a file with a list of words or documents, calculates a matrix of cosine distances.</li>
    
    <li><b><a href={{ url_for('weblingtools_blueprint.get_nearest_neighbors') }}>Nearest neighbors</a>: </b>
    Given a word, calculates the nearest neighbors.</li>
    
    </ul>

</div> <!--/col-->    
</div><!--/row-->
    
{% endblock %}

weblingtools/weblingtools_app/templates/results_file.html
{% extends "base.html" %}
{% block content %}

<div class="row">
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

<h2>Results</h2>

    {% if errormsg %}
        <div class="alert alert-warning" role="alert">
            <strong>Error:</strong> {{ errormsg }}
        </div>  
    {% endif %} 
    
    {% if warningmsg %}
        <div class="alert alert-info" role="alert">
            <strong>Warning:</strong> {{ warningmsg }}
        </div>  
    {% endif %} 

{% if file_for_download %}

<p><b>Download the results (link will expire after 15 minutes):</b></p>
<p><a href="/download/{{ file_for_download }}">Download results</a></p>

{% endif %}

</div> <!--/col-->    
</div><!--/row-->
    
{% endblock %}

weblingtools/weblingtools_app/templates/simple.html
{% extends "base.html" %}
{% block content %}

<div class="row">
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

    <h2>Simple text feature extraction</h2>   
    
	
    {% if errormsg %}
        <div class="alert alert-warning" role="alert">
            <strong>Error:</strong> {{ errormsg }}
        </div>  
    {% endif %} 
    
    {% if warningmsg %}
        <div class="alert alert-info" role="alert">
            <strong>Warning:</strong> {{ warningmsg }}
        </div>  
    {% endif %} 

	<p>Here you can extract linguistic features from a text. Write your text below (max {{max_text_size}} characteres).</p>

	<p>The list of features extracted by the tool (and their ranges) can be found in the <a href="/help">Help</a> page.</p>
    
    <form action="{{ url_for('weblingtools_blueprint.process_simple') }}" method="post" >
    
        <div class="form-group col-sm-8 col-md-8 col-lg-8"> 
            <label for="text">Text:</label>
            <textarea  class="form-control" rows=5 id="text" name="text" placeholder="Hello World!"></textarea>
        </div>
        
        <div class="clearfix"></div>
        
        <div class="form-group col-sm-4 col-md-4">
	        <label for="vectorspace_name">Vector space</label>
	        <select class="form-control" name="vectorspace_name" id="vectorspace_name">
	        {% for vs in vectorspaces %}
	            <option value="{{vs.name}}">{{vs.name}}: {{vs.description}}</option>
	        {% endfor %}
	        </select>
	        <p class="help-block">Choose the desired vector space</p>
    	</div>
        
        <div class="form-group col-sm-12 col-md-12 col-lg-12">
            <input type="submit" class="btn btn-default" value="Analyze" />
        </div>

    
    </form>    
    
    
</div> <!--/col-->    
</div><!--/row-->
    
{% endblock %}